name: Action
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
            - name: List out files before
              run: ls -a
            - uses: actions/checkout@v3
            - name: List files After
              run: ls -a